# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_processing.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\x12\x0fimageprocessing\"5\n\nImageChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x19\n\x11processing_option\x18\x02 \x01(\t\"D\n\x13ProcessImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x19\n\x11processing_option\x18\x02 \x01(\t\"=\n\x14ProcessImageResponse\x12\x17\n\x0fprocessed_image\x18\x01 \x01(\x0c\x12\x0c\n\x04logs\x18\x02 \x03(\t\":\n\tImageData\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x19\n\x11processing_option\x18\x02 \x01(\t\"B\n\x14ProcessImagesRequest\x12*\n\x06images\x18\x01 \x03(\x0b\x32\x1a.imageprocessing.ImageData\"[\n\x15ProcessImagesResponse\x12\x34\n\x10processed_images\x18\x01 \x03(\x0b\x32\x1a.imageprocessing.ImageData\x12\x0c\n\x04logs\x18\x02 \x03(\t2\x9d\x02\n\x0fImageProcessing\x12M\n\x11ProcessImageChunk\x12\x1b.imageprocessing.ImageChunk\x1a\x1b.imageprocessing.ImageChunk\x12[\n\x0cProcessImage\x12$.imageprocessing.ProcessImageRequest\x1a%.imageprocessing.ProcessImageResponse\x12^\n\rProcessImages\x12%.imageprocessing.ProcessImagesRequest\x1a&.imageprocessing.ProcessImagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECHUNK']._serialized_start=43
  _globals['_IMAGECHUNK']._serialized_end=96
  _globals['_PROCESSIMAGEREQUEST']._serialized_start=98
  _globals['_PROCESSIMAGEREQUEST']._serialized_end=166
  _globals['_PROCESSIMAGERESPONSE']._serialized_start=168
  _globals['_PROCESSIMAGERESPONSE']._serialized_end=229
  _globals['_IMAGEDATA']._serialized_start=231
  _globals['_IMAGEDATA']._serialized_end=289
  _globals['_PROCESSIMAGESREQUEST']._serialized_start=291
  _globals['_PROCESSIMAGESREQUEST']._serialized_end=357
  _globals['_PROCESSIMAGESRESPONSE']._serialized_start=359
  _globals['_PROCESSIMAGESRESPONSE']._serialized_end=450
  _globals['_IMAGEPROCESSING']._serialized_start=453
  _globals['_IMAGEPROCESSING']._serialized_end=738
# @@protoc_insertion_point(module_scope)
